{
  "formatVersion": "1.1",
  "component": {
    "group": "com.datalogic.aladdin",
    "module": "aladdin-sdk",
    "version": "2.4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aladdin-sdk-2.4.9.aar",
          "url": "aladdin-sdk-2.4.9.aar",
          "size": 509922,
          "sha512": "29486d3a61d5a42a92aa67445625ec8f3f34aacf22cfbe5b3d25c787b7ba4a4815d25efc3b13da5ddf38246729272c3080384aaaf29e61cdb8e6ba2bc0167a13",
          "sha256": "88669338e3c68d06bb6b9a51df8b6357976a5b098d760e73e8256d1318da44b3",
          "sha1": "a4a896d3eac3567c3f276299aa1d468d935983a7",
          "md5": "4bf6067831dc95b4762fc596eab80ebd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.github.mik3y",
          "module": "usb-serial-for-android",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.1"
          }
        },
        {
          "group": "uk.org.okapibarcode",
          "module": "okapibarcode",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aladdin-sdk-2.4.9.aar",
          "url": "aladdin-sdk-2.4.9.aar",
          "size": 509922,
          "sha512": "29486d3a61d5a42a92aa67445625ec8f3f34aacf22cfbe5b3d25c787b7ba4a4815d25efc3b13da5ddf38246729272c3080384aaaf29e61cdb8e6ba2bc0167a13",
          "sha256": "88669338e3c68d06bb6b9a51df8b6357976a5b098d760e73e8256d1318da44b3",
          "sha1": "a4a896d3eac3567c3f276299aa1d468d935983a7",
          "md5": "4bf6067831dc95b4762fc596eab80ebd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aladdin-sdk-2.4.9-sources.jar",
          "url": "aladdin-sdk-2.4.9-sources.jar",
          "size": 154262,
          "sha512": "6a9f668d4150c7d29e9848d1542f3ff72ff97ff4d133c295d68382916c5d3ccb61063000944e300ddd8d28b4bd0836067aa2fa5bf2815bd10dbaf0a3c2661e37",
          "sha256": "8ca5968a17c7c45e98ffae2f169dce395345cc13d262f01bd30d375860efd3ca",
          "sha1": "c951e37f3f110c41d0970dd9b1ff322f912067ea",
          "md5": "6d02af7b1080f724f067e8b5bc5123a5"
        }
      ]
    }
  ]
}
