{
  "formatVersion": "1.1",
  "component": {
    "group": "com.datalogic.aladdin",
    "module": "aladdin-sdk",
    "version": "2.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aladdin-sdk-2.4.5.aar",
          "url": "aladdin-sdk-2.4.5.aar",
          "size": 503763,
          "sha512": "abf1c02e0b6baed771f1c8a4cf77d8c03b6f5181d42358f1eb92c4d4d82fbef439f18b723b48d90cdac5bb24c122dbc53dbfb94783c7e754ba7fecc7160e67d6",
          "sha256": "42780f4d013aafb10cdca95d89baf700b9a880a0419e25edadd43ba549677b61",
          "sha1": "71807d6daccbe60bfcba0d2ab200161bda8bcdc6",
          "md5": "b3d6bdc35bf08aed6556a4f2fc2c76ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.github.mik3y",
          "module": "usb-serial-for-android",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.1"
          }
        },
        {
          "group": "uk.org.okapibarcode",
          "module": "okapibarcode",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aladdin-sdk-2.4.5.aar",
          "url": "aladdin-sdk-2.4.5.aar",
          "size": 503763,
          "sha512": "abf1c02e0b6baed771f1c8a4cf77d8c03b6f5181d42358f1eb92c4d4d82fbef439f18b723b48d90cdac5bb24c122dbc53dbfb94783c7e754ba7fecc7160e67d6",
          "sha256": "42780f4d013aafb10cdca95d89baf700b9a880a0419e25edadd43ba549677b61",
          "sha1": "71807d6daccbe60bfcba0d2ab200161bda8bcdc6",
          "md5": "b3d6bdc35bf08aed6556a4f2fc2c76ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aladdin-sdk-2.4.5-sources.jar",
          "url": "aladdin-sdk-2.4.5-sources.jar",
          "size": 150817,
          "sha512": "6dc566a61db7a648f0c28b88ec8dda7c4cb5bdb1db7379202379f4ebaf1f05f48a31626f16e9a1a41e76a736c0b2de393279eb096072935a1666b047799b9fa5",
          "sha256": "7545ac062d23969416feaaa557362ae05b9cbc63c5d574bdc8359a09791d55b8",
          "sha1": "469f503ab37fc5793713fc8bdc476e03205a791f",
          "md5": "670d0166f934c5f233c15ed8d30b4590"
        }
      ]
    }
  ]
}
